### ISSUE TITLE
Diagrama de Sequencia

### ISSUE THREAD

**Issue by iabreuda** [ESEGroup/Peru#8]

**Comment by cfleao** [comment]
Feitos os diagramas de sequência dos seguintes casos de uso:
- Cadastrar Usuário;
- Cadastrar Anúncio;
- Alterar Anúncio;
- Remover Anúncio;
- Aprovar Anúncio;
- Buscar Anúncio;
- Interagir com Anúncio;
- Oferta de Bolsa.
